version: '3'
services:  
  micro-api:
    command:  api --handler=rpc
    image: microhq/micro:latest
    ports:
      - "8080:8080"
  micro-web:
    command:  web
    image: microhq/micro:latest
    ports:
      - "8082:8082"
  cinema:
    build:
      context: .
      dockerfile: service.Dockerfile
      args:
        service: cinema
  screening:
     build:
        context: .
        dockerfile: service.Dockerfile
        args:
           service: screening
  reservation:
      build:
          context: .
          dockerfile: service.Dockerfile
          args:
              service: reservation
  user:
    build:
      context: .
      dockerfile: service.Dockerfile
      args: 
        service: user
  movie:
    build:
      context: .
      dockerfile: service.Dockerfile
      args: 
        service: movie
