// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: srv/sample/proto/sample.proto

package sample

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Sample service

type SampleService interface {
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResult, error)
}

type sampleService struct {
	c    client.Client
	name string
}

func NewSampleService(name string, c client.Client) SampleService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "sample"
	}
	return &sampleService{
		c:    c,
		name: name,
	}
}

func (c *sampleService) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResult, error) {
	req := c.c.NewRequest(c.name, "Sample.List", in)
	out := new(ListResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Sample service

type SampleHandler interface {
	List(context.Context, *ListRequest, *ListResult) error
}

func RegisterSampleHandler(s server.Server, hdlr SampleHandler, opts ...server.HandlerOption) error {
	type sample interface {
		List(ctx context.Context, in *ListRequest, out *ListResult) error
	}
	type Sample struct {
		sample
	}
	h := &sampleHandler{hdlr}
	return s.Handle(s.NewHandler(&Sample{h}, opts...))
}

type sampleHandler struct {
	SampleHandler
}

func (h *sampleHandler) List(ctx context.Context, in *ListRequest, out *ListResult) error {
	return h.SampleHandler.List(ctx, in, out)
}
